imagePullSecrets:
  - name: harbor-swarm-registry-secret
  - name: harbor-registry-secret

image:
  repository: postgres
  tag: 14.8
  pullPolicy: IfNotPresent

env:
  POSTGRES_USER: nkiver
  POSTGRES_PASSWORD: nkiver
  POSTGRES_DB: postgres

ports:
  - name: postgres
    containerPort: 5432
    protocol: TCP
