# https://gitlab.wildberries.ru/devops/ci/templates/-/blob/master/README.md
.template_repo: &repo
  project: &ci_tmpl 'devops/ci/templates'
  ref: &ci_tmpl_vers 'v3.6.1'

variables:
  # Mandatory vars. Do not change this
  CI_TMPL_PROJECT: *ci_tmpl
  CI_TMPL_PROJECT_VERSION: *ci_tmpl_vers

  #
  # Language specific vars. Most likly need to specify
  # 
  GO_MAIN_PATH: ./app
  GO_VER: "1.20"
  ALPINE_VER: "3.17"
  GO_TEST_FLAGS: "-mod=readonly"

  #
  # Mandatory vars. Specify them
  #

  # Helm chart name. List of chart can be found here https://gitlab.wildberries.ru/devops/helm/charts
  # common-deploy is default chart
  # common-job is additional chart, his version is specified using CI_TMPL_HELM_CHART_COMMON_JOB_VERSION
  CI_TMPL_HELM_CHARTS: "common-deploy@v4.2.0"
  # You can specify chart version using special variable
  # Setting common-job version to v1.0.1
  # CI_TMPL_HELM_CHART_COMMON_JOB_VERSION: 1.0.1
  # list of services for build & deploy
  # go-tmpl, go-tmpl-2, go-tmpl-common will be deployed with common-deploy chart because this is default chart
  # go-tmpl-job will be deployed with common-job chart because of explicit chart definition using @ character
  CI_TMPL_HELM_RELEASE_NAMES: ""
  CI_TMPL_HELM_RELEASE_NAMESPACE: swarm
  # List of clusters for deploy
  CI_TMPL_KUBE_CLUSTERS_DEV: ""
  CI_TMPL_KUBE_CLUSTERS_STAGE: ""
  CI_TMPL_KUBE_CLUSTERS_PROD: "k8s.prod-dl,k8s.prod-dp"

  # Harbor project name
  REGISTRY_PROJECT: "swarm"

  #
  # Optional example vars
  #

  # HHX custom var example
  # see deploy/go-tmpl/common-go-tmpl-values.yml#L4
  CI_TMPL_HELM_CUSTOM_MY_VAR1: "myvalue"
  # Change deploy jobs appearance in pipeline
  CI_TMPL_DEPLOY_GROUPING: per-service


include:
  - {<<: *repo, file: /global.yml}
  - {<<: *repo, file: /checks.yml}
  - {<<: *repo, file: /go/global.yml}
  - {<<: *repo, file: /go/lint.yml}
  - {<<: *repo, file: /go/test.yml}
  - {<<: *repo, file: /docker/build.yml}
  - {<<: *repo, file: /helm/deploy.yml}

stages:
  - checks
  - lint
  - test
  - generate dynamic pipeline
  - build
  - deploy

build:
  variables:
    CI_TMPL_HELM_RELEASE_NAMES: "sgroups,to-nft"

deploy:

  rules:
    - if: $CI_COMMIT_BRANCH = master
      variables:
        CI_TMPL_ENVIRONMENT_NAME: prod
        CI_TMPL_HELM_RELEASE_NAMES: "sgroups"

