imagePullSecrets:
  - name: harbor-swarm-registry-secret
  - name: harbor-registry-secret

image:
  repository: {{.Helm.Release.Image}}
  tag: {{.Helm.Release.Tag}}
  pullPolicy: IfNotPresent

command:
  - /app/to-nft

args:
  - --config
  - /config/config.yaml

securityContext:
  privileged: true
  runAsUser: 0

config:
  files:
    config.yaml:
      data: |-
        ---
        graceful-shutdown: 10s

        logger:
          # log level [optional]
          level: INFO

        extapi:
          svc:
            def-daial-duration: 10s
            sgroups:
              # sgroups service dial duration [optional]
              dial-duration: 3s
              # service address [mandatory]
              address: tcp://sgroups:80
              # interval(duration) backend sync-status check [mandatory]
              check-sync-status: 15s
