imagePullSecrets:
  - name: harbor-swarm-registry-secret
  - name: harbor-registry-secret

image:
  repository: {{.Helm.Release.Image}}
  tag: {{.Helm.Release.Tag}}
  pullPolicy: IfNotPresent

args:
  - --config=/config/config.yaml

config:
  files:
    config.yaml:
      data: |-
        ---
        graceful-shutdown: 10s

        logger:
          # log level [optional]
          level: INFO

        extapi:
          svc:
            def-daial-duration: 10s
            sgroups:
              # sgroups service dial duration [optional]
              dial-duration: 3s
              # service address [mandatory]
              address: tcp://{{ .Helm.Release.Namespace }}-ingress-controller.{{ .Helm.Release.Namespace }}.svc.{{ .Helm.Release.Cluster }}:80
              # interval(duration) backend sync-status check [mandatory]
              check-sync-status: 15s
